

trigger: none
#- master

resources:
- repo: self


variables:
  ImageName: 'lidorlg/sample-app-python'

stages:
# - stage: Build
#   displayName: Build image
#   jobs:
#   - job: Build
#     displayName: Build
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#     - task: Docker@2    
#       inputs:
#         containerRegistry: 'Docker Hub'
#         repository: '$(ImageName)'
#         command: 'build'
#         DockerFile: '**/Dockerfile'
#       displayName: "Build the Docker image number $(Build.BuildId)"
#     - task: Docker@2
#       inputs:
#         containerRegistry: 'Docker Hub'
#         repository: '$(ImageName)'
#         command: 'build'
#         Dockerfile: '**/Dockerfile'
#         tags: 'latest'
#       displayName: 'Build the latest Docker image'
#     - task: Docker@2      
#       inputs:
#         containerRegistry: 'Docker Hub'
#         repository: '$(ImageName)'
#         command: 'push'
        
#       condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
#       displayName: "Push the Docker image number $(Build.BuildId) to Dockerhub"

#     - task: Docker@2
#       inputs:
#         containerRegistry: 'Docker Hub'
#         repository: '$(ImageName)'
#         command: 'push'
#         tags: 'latest'
#       condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
#       displayName: 'Push the latest Docker image to Dockerhub'
    
- stage: Provision
  displayName: Provision with Terraform
  jobs:
  - job: Provision
    displayName: Provision
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - checkout: self
      displayName: 'Checkout repository'
    
    
    # - task: CmdLine@2
    #   displayName: Create ssh key
    #   inputs:
    #     script: "ssh-keygen -t rsa -b 4096 -N '' -f $(System.DefaultWorkingDirectory)/terraform/key <<< y"
    # - task: CmdLine@2
    #   displayName: check to see ssh keys
    #   inputs:
    #     script: 'ls $(System.DefaultWorkingDirectory)/terraform/'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendServiceAWS: 'aws'
        backendAWSBucketName: 'states-tf1'
        backendAWSKey: 'tf/dev/terraform.tfstate'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Validate'
      inputs:
        provider: 'aws'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'aws'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        commandOptions: '-out=tfplan'
        environmentServiceNameAWS: 'aws'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply'
      inputs:
        provider: 'aws'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        commandOptions: '-auto-approve -input=false tfplan'
        environmentServiceNameAWS: 'aws'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/terraform'
        artifact: 'published'
        publishLocation: 'pipeline'

 
        


